ALTER TABLE deployment
    ADD COLUMN IF NOT EXISTS pid INTEGER,
    ADD COLUMN IF NOT EXISTS config_json JSONB,
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS stopped_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS exit_code INTEGER,
    ADD COLUMN IF NOT EXISTS log_path VARCHAR(255),
    ADD COLUMN IF NOT EXISTS module_name VARCHAR(50),
    ADD COLUMN IF NOT EXISTS deployment_token VARCHAR(64) UNIQUE,
    ADD COLUMN IF NOT EXISTS org_id INTEGER,
    ADD COLUMN IF NOT EXISTS region_id INTEGER;
