-- ============================================
-- AIoT Device Management Platform Schema
-- PostgreSQL 15+
-- Generated by Claude Code Team
-- ============================================

-- ============================================
-- 0. DICTIONARY: Device Types
-- ============================================
CREATE TABLE IF NOT EXISTS dict_device_type (
    id              SMALLSERIAL PRIMARY KEY,
    name            VARCHAR(32) NOT NULL UNIQUE,
    description     VARCHAR(128)
);

INSERT INTO dict_device_type (name, description) VALUES
    ('Camera', 'IP Camera'),
    ('NVR', 'Network Video Recorder'),
    ('DVR', 'Digital Video Recorder'),
    ('Encoder', 'Video Encoder'),
    ('Decoder', 'Video Decoder'),
    ('Storage', 'Storage Device');

-- ============================================
-- 1. ORGANIZATIONS (Hierarchical)
-- ============================================
CREATE TABLE IF NOT EXISTS org (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    code            VARCHAR(32) UNIQUE,
    parent_id       BIGINT REFERENCES org(id) ON DELETE SET NULL,
    level           SMALLINT NOT NULL DEFAULT 0,
    sort_order      SMALLINT NOT NULL DEFAULT 0,
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(parent_id, name)
);

CREATE INDEX idx_org_parent ON org(parent_id);
CREATE INDEX idx_org_level ON org(level);
CREATE INDEX idx_org_status ON org(status);
CREATE INDEX idx_org_code ON org(code);

-- ============================================
-- 2. ROLES
-- ============================================
CREATE TABLE IF NOT EXISTS role (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(64) NOT NULL,
    code            VARCHAR(32) NOT NULL UNIQUE,
    description     VARCHAR(256),
    permissions     JSONB NOT NULL DEFAULT '[]',
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_role_code ON role(code);
CREATE INDEX idx_role_status ON role(status);

-- ============================================
-- 3. USERS
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(64) NOT NULL UNIQUE,
    password_hash   VARCHAR(256) NOT NULL,
    phone           VARCHAR(32),
    email           VARCHAR(128),
    gender          SMALLINT DEFAULT 0 CHECK (gender IN (0, 1, 2)),
    avatar          VARCHAR(512),
    org_id          BIGINT REFERENCES org(id) ON DELETE SET NULL,
    role_id         BIGINT REFERENCES role(id) ON DELETE SET NULL,
    status          SMALLINT NOT NULL DEFAULT 1,
    last_login      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_org ON users(org_id);
CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_deleted ON users(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_users_org_role ON users(org_id, role_id);

-- ============================================
-- 4. DEVICE GROUPS (Hierarchical)
-- ============================================
CREATE TABLE IF NOT EXISTS device_group (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    parent_id       BIGINT REFERENCES device_group(id) ON DELETE CASCADE,
    sort_order      SMALLINT NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(parent_id, name)
);

CREATE INDEX idx_device_group_parent ON device_group(parent_id);
CREATE INDEX idx_device_group_deleted ON device_group(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 5. DEVICES
-- ============================================
CREATE TABLE IF NOT EXISTS device (
    id                      BIGSERIAL PRIMARY KEY,
    device_name             VARCHAR(128) NOT NULL,
    device_sn               VARCHAR(128),
    device_ip               VARCHAR(64),
    device_port             INTEGER,
    device_type             SMALLINT NOT NULL REFERENCES dict_device_type(id),
    firmware_version        VARCHAR(64),
    department              VARCHAR(128),
    product_type            VARCHAR(64),
    cpu_cores               SMALLINT DEFAULT 0,
    cpu_usage               DECIMAL(5,2) DEFAULT 0,
    memory_size             BIGINT DEFAULT 0,
    memory_usage            BIGINT DEFAULT 0,
    disk_size               BIGINT DEFAULT 0,
    disk_usage              BIGINT DEFAULT 0,
    video_source_count      SMALLINT DEFAULT 0,
    online_status           SMALLINT NOT NULL DEFAULT 0 CHECK (online_status IN (0, 1, 2)),
    last_heartbeat_at      TIMESTAMPTZ,
    auth_status             SMALLINT DEFAULT 0,
    auth_expire_time        TIMESTAMPTZ,
    region_id               BIGINT REFERENCES region(id) ON DELETE SET NULL,
    org_id                  BIGINT REFERENCES org(id) ON DELETE SET NULL,
    deleted_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_device_name ON device(device_name);
CREATE INDEX idx_device_ip ON device(device_ip);
CREATE INDEX idx_device_type ON device(device_type);
CREATE INDEX idx_device_online ON device(online_status);
CREATE INDEX idx_device_department ON device(department);
CREATE INDEX idx_device_region ON device(region_id);
CREATE INDEX idx_device_org ON device(org_id);
CREATE INDEX idx_device_deleted ON device(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_device_online_heartbeat ON device(online_status, last_heartbeat_at) WHERE online_status = 1;
CREATE INDEX idx_device_org_online ON device(org_id, online_status);

-- ============================================
-- 6. DEVICE-GROUP MEMBERSHIP (Junction)
-- ============================================
CREATE TABLE IF NOT EXISTS device_group_member (
    device_id       BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    group_id        BIGINT NOT NULL REFERENCES device_group(id) ON DELETE CASCADE,
    PRIMARY KEY (device_id, group_id)
);

CREATE INDEX idx_device_group_member_device ON device_group_member(device_id);
CREATE INDEX idx_device_group_member_group ON device_group_member(group_id);

-- ============================================
-- 7. REGIONS (Hierarchical)
-- ============================================
CREATE TABLE IF NOT EXISTS region (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    code            VARCHAR(32) NOT NULL UNIQUE,
    parent_id       BIGINT REFERENCES region(id) ON DELETE CASCADE,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(parent_id, name)
);

CREATE INDEX idx_region_code ON region(code);
CREATE INDEX idx_region_parent ON region(parent_id);
CREATE INDEX idx_region_deleted ON region(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 8. DATA SOURCES
-- ============================================
CREATE TABLE IF NOT EXISTS data_source (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    type            VARCHAR(32) NOT NULL,
    config          JSONB NOT NULL DEFAULT '{}',
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_data_source_type ON data_source(type);
CREATE INDEX idx_data_source_status ON data_source(status);
CREATE INDEX idx_data_source_deleted ON data_source(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 9. ALGORITHMS
-- ============================================
CREATE TABLE IF NOT EXISTS algorithm (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    type            VARCHAR(32) NOT NULL,
    config          JSONB NOT NULL DEFAULT '{}',
    service_url     VARCHAR(512),
    annotation_url  VARCHAR(512),
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_algorithm_type ON algorithm(type);
CREATE INDEX idx_algorithm_status ON algorithm(status);
CREATE INDEX idx_algorithm_deleted ON algorithm(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 10. ALGORITHM EVENTS
-- ============================================
CREATE TABLE IF NOT EXISTS algorithm_event (
    id              BIGSERIAL PRIMARY KEY,
    event_name      VARCHAR(128) NOT NULL,
    algorithm_id    BIGINT NOT NULL REFERENCES algorithm(id) ON DELETE CASCADE,
    config          JSONB NOT NULL DEFAULT '{}',
    trigger_type    VARCHAR(32) NOT NULL,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_algorithm_event_algorithm ON algorithm_event(algorithm_id);
CREATE INDEX idx_algorithm_event_trigger ON algorithm_event(trigger_type);
CREATE INDEX idx_algorithm_event_deleted ON algorithm_event(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_algorithm_event_algorithm_trigger ON algorithm_event(algorithm_id, trigger_type);

-- ============================================
-- 11. ALGORITHM SERVICES
-- ============================================
CREATE TABLE IF NOT EXISTS algorithm_service (
    id                  BIGSERIAL PRIMARY KEY,
    service_id          VARCHAR(64) NOT NULL UNIQUE,
    service_name        VARCHAR(128) NOT NULL,
    algorithm_id        BIGINT REFERENCES algorithm(id) ON DELETE SET NULL,
    service_address     JSONB NOT NULL DEFAULT '[]',
    algorithm_config    JSONB NOT NULL DEFAULT '{}',
    deleted_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_algorithm_service_service_id ON algorithm_service(service_id);
CREATE INDEX idx_algorithm_service_algorithm ON algorithm_service(algorithm_id);
CREATE INDEX idx_algorithm_service_deleted ON algorithm_service(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 12. LINKAGE RULES
-- ============================================
CREATE TABLE IF NOT EXISTS linkage_rule (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    conditions      JSONB NOT NULL DEFAULT '[]',
    actions         JSONB NOT NULL DEFAULT '[]',
    priority        SMALLINT NOT NULL DEFAULT 0,
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_linkage_rule_priority ON linkage_rule(priority);
CREATE INDEX idx_linkage_rule_status ON linkage_rule(status);
CREATE INDEX idx_linkage_rule_deleted ON linkage_rule(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_linkage_rule_active ON linkage_rule(priority) WHERE status = 1;

-- ============================================
-- 13. LINKAGE HISTORY (Partitioned by month)
-- ============================================
CREATE TABLE IF NOT EXISTS linkage_history (
    id              BIGSERIAL,
    rule_id         BIGINT NOT NULL,
    trigger_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    trigger_data    JSONB,
    action_result   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, trigger_time),
    FOREIGN KEY (rule_id) REFERENCES linkage_rule(id) ON DELETE SET NULL
) PARTITION BY RANGE (trigger_time);

-- Create partitions for 2026
CREATE TABLE IF NOT EXISTS linkage_history_2026_01 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_02 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_03 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_04 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_05 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_06 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_07 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_08 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_09 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_10 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_11 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS linkage_history_2026_12 PARTITION OF linkage_history
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- Partitioned indexes (propagate to all partitions)
CREATE INDEX idx_linkage_history_rule ON linkage_history(rule_id);
CREATE INDEX idx_linkage_history_trigger_time ON linkage_history(trigger_time);

-- ============================================
-- 14. NOTIFICATIONS
-- ============================================
CREATE TABLE IF NOT EXISTS notification (
    id              BIGSERIAL PRIMARY KEY,
    type            VARCHAR(32) NOT NULL,
    title           VARCHAR(256) NOT NULL,
    content         TEXT,
    recipients      JSONB NOT NULL DEFAULT '[]',
    status          SMALLINT NOT NULL DEFAULT 0,
    sent_at         TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_type ON notification(type);
CREATE INDEX idx_notification_status ON notification(status);
CREATE INDEX idx_notification_created ON notification(created_at);
CREATE INDEX idx_notification_deleted ON notification(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 15. MENUS (Hierarchical)
-- ============================================
CREATE TABLE IF NOT EXISTS menu (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(64) NOT NULL,
    path            VARCHAR(256),
    parent_id       BIGINT REFERENCES menu(id) ON DELETE CASCADE,
    icon            VARCHAR(64),
    sort_order      SMALLINT NOT NULL DEFAULT 0,
    permissions     VARCHAR(256),
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_menu_parent ON menu(parent_id);
CREATE INDEX idx_menu_path ON menu(path);
CREATE INDEX idx_menu_deleted ON menu(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 16. RESOURCES (API Permissions)
-- ============================================
CREATE TABLE IF NOT EXISTS resource (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(64) NOT NULL,
    type            VARCHAR(32) NOT NULL DEFAULT 'api',
    path            VARCHAR(256) NOT NULL,
    method          VARCHAR(16) NOT NULL DEFAULT 'GET',
    description     VARCHAR(256),
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(path, method)
);

CREATE INDEX idx_resource_path_method ON resource(path, method);
CREATE INDEX idx_resource_deleted ON resource(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 17. ROLE-MENU JUNCTION
-- ============================================
CREATE TABLE IF NOT EXISTS role_menu (
    role_id         BIGINT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    menu_id         BIGINT NOT NULL REFERENCES menu(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, menu_id)
);

CREATE INDEX idx_role_menu_role ON role_menu(role_id);
CREATE INDEX idx_role_menu_menu ON role_menu(menu_id);

-- ============================================
-- 18. ROLE-RESOURCE JUNCTION
-- ============================================
CREATE TABLE IF NOT EXISTS role_resource (
    role_id         BIGINT NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    resource_id     BIGINT NOT NULL REFERENCES resource(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, resource_id)
);

CREATE INDEX idx_role_resource_role ON role_resource(role_id);
CREATE INDEX idx_role_resource_resource ON role_resource(resource_id);

-- ============================================
-- 19. LICENSE FILES
-- ============================================
CREATE TABLE IF NOT EXISTS license (
    id              BIGSERIAL PRIMARY KEY,
    license_key     VARCHAR(256) NOT NULL UNIQUE,
    customer_name   VARCHAR(128),
    expire_date     TIMESTAMPTZ NOT NULL,
    device_limit    INTEGER NOT NULL DEFAULT 0 CHECK (device_limit >= 0),
    features        JSONB NOT NULL DEFAULT '{}',
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_license_key ON license(license_key);
CREATE INDEX idx_license_expire ON license(expire_date);
CREATE INDEX idx_license_deleted ON license(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 20. FIRMWARE
-- ============================================
CREATE TABLE IF NOT EXISTS firmware (
    id              BIGSERIAL PRIMARY KEY,
    version         VARCHAR(64) NOT NULL UNIQUE,
    file_path       VARCHAR(512) NOT NULL,
    file_size       BIGINT NOT NULL,
    checksum        VARCHAR(64) NOT NULL CHECK (length(checksum) = 64 AND checksum ~ '^[a-f0-9]+$'),
    description     TEXT,
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_firmware_version ON firmware(version);
CREATE INDEX idx_firmware_deleted ON firmware(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 21. SYSTEM SETTINGS
-- ============================================
CREATE TABLE IF NOT EXISTS system_setting (
    id              BIGSERIAL PRIMARY KEY,
    category        VARCHAR(32) NOT NULL,
    key             VARCHAR(64) NOT NULL,
    value           TEXT,
    description     VARCHAR(256),
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(category, key)
);

CREATE INDEX idx_system_setting_category ON system_setting(category);
CREATE INDEX idx_system_setting_deleted ON system_setting(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 22. OPERATION LOGS (Partitioned by month)
-- ============================================
CREATE TABLE IF NOT EXISTS operation_log (
    id              BIGSERIAL,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    action          VARCHAR(64) NOT NULL,
    module          VARCHAR(64) NOT NULL,
    resource_id     BIGINT,
    ip              VARCHAR(64),
    user_agent      VARCHAR(512),
    request_data    JSONB,
    response_data   JSONB,
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Create partitions for 2026
CREATE TABLE IF NOT EXISTS operation_log_2026_01 PARTITION OF operation_log
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_02 PARTITION OF operation_log
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_03 PARTITION OF operation_log
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_04 PARTITION OF operation_log
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_05 PARTITION OF operation_log
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_06 PARTITION OF operation_log
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_07 PARTITION OF operation_log
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_08 PARTITION OF operation_log
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_09 PARTITION OF operation_log
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_10 PARTITION OF operation_log
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_11 PARTITION OF operation_log
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS operation_log_2026_12 PARTITION OF operation_log
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- Partitioned indexes (propagate to all partitions)
CREATE INDEX idx_operation_log_user ON operation_log(user_id);
CREATE INDEX idx_operation_log_action ON operation_log(action);
CREATE INDEX idx_operation_log_module ON operation_log(module);
CREATE INDEX idx_operation_log_created ON operation_log(created_at);

-- ============================================
-- 23. REFRESH TOKENS (for JWT auth)
-- ============================================
CREATE TABLE IF NOT EXISTS refresh_token (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      VARCHAR(256) NOT NULL UNIQUE,
    device_info     VARCHAR(256),
    ip              VARCHAR(64),
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_token_user ON refresh_token(user_id);
CREATE INDEX idx_refresh_token_hash ON refresh_token(token_hash);
CREATE INDEX idx_refresh_token_expires ON refresh_token(expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_token_user_created ON refresh_token(user_id, created_at);

-- ============================================
-- 24. DEPLOYMENTS
-- ============================================
CREATE TABLE IF NOT EXISTS deployment (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    type            VARCHAR(32) NOT NULL,
    target_ids      JSONB NOT NULL DEFAULT '[]',
    config          JSONB NOT NULL DEFAULT '{}',
    status          SMALLINT NOT NULL DEFAULT 1,
    progress        SMALLINT DEFAULT 0,
    total_targets   INTEGER DEFAULT 0,
    succeeded       INTEGER DEFAULT 0,
    failed          INTEGER DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_deployment_status ON deployment(status);
CREATE INDEX idx_deployment_created ON deployment(created_at);
CREATE INDEX idx_deployment_deleted ON deployment(deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================
-- 25. DEPLOYMENT ANNOTATIONS
-- ============================================
CREATE TABLE IF NOT EXISTS deployment_annotation (
    id              BIGSERIAL PRIMARY KEY,
    deployment_id   BIGINT NOT NULL REFERENCES deployment(id) ON DELETE CASCADE,
    device_id       BIGINT REFERENCES device(id) ON DELETE SET NULL,
    type            VARCHAR(32),
    polygon         JSONB,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_deployment_annotation_deployment ON deployment_annotation(deployment_id);
CREATE INDEX idx_deployment_annotation_device ON deployment_annotation(device_id);

-- ============================================
-- 26. DEVICE ACCESS PLATFORMS (GB28181/ONVIF)
-- ============================================
CREATE TABLE IF NOT EXISTS device_platform (
    id              BIGSERIAL PRIMARY KEY,
    vendor          VARCHAR(64),
    tenant_name     VARCHAR(128),
    platform_type   VARCHAR(32) NOT NULL DEFAULT 'GB28181',
    host            VARCHAR(256),
    port            INTEGER,
    app_key         VARCHAR(256),
    app_secret      VARCHAR(256),
    api_version     VARCHAR(32),
    platform_version VARCHAR(32),
    org_id          BIGINT REFERENCES org(id) ON DELETE SET NULL,
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_device_platform_status ON device_platform(status);
CREATE INDEX idx_device_platform_deleted ON device_platform(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX idx_device_platform_org ON device_platform(org_id);

-- ============================================
-- AUTOMATED PARTITION CREATION FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION make_partition_if_missing(
    table_name TEXT,
    partition_date DATE
) RETURNS VOID AS $$
DECLARE
    partition_suffix TEXT;
    start_date DATE;
    end_date DATE;
    partition_exists BOOLEAN;
BEGIN
    partition_suffix := to_char(partition_date, 'YYYY_MM');
    start_date := date_trunc('month', partition_date);
    end_date := start_date + interval '1 month';

    EXECUTE format(
        'SELECT EXISTS (SELECT 1 FROM pg_class WHERE relname = $1)',
        table_name || '_' || partition_suffix
    ) INTO partition_exists;

    IF NOT partition_exists THEN
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
            table_name || '_' || partition_suffix,
            table_name,
            start_date,
            end_date
        );
        RAISE NOTICE 'Created partition: %', table_name || '_' || partition_suffix;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to ensure partitions exist for the next N months
CREATE OR REPLACE FUNCTION ensure_future_partitions(
    table_name TEXT,
    months_ahead INTEGER DEFAULT 3
) RETURNS VOID AS $$
DECLARE
    i INTEGER;
    target_date DATE;
BEGIN
    FOR i IN 0..months_ahead LOOP
        target_date := date_trunc('month', CURRENT_DATE) + (i || ' months')::interval;
        PERFORM make_partition_if_missing(table_name, target_date);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- TRIGGER: Auto-update updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER tr_org_updated BEFORE UPDATE ON org FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_role_updated BEFORE UPDATE ON role FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_device_updated BEFORE UPDATE ON device FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_device_group_updated BEFORE UPDATE ON device_group FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_region_updated BEFORE UPDATE ON region FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_data_source_updated BEFORE UPDATE ON data_source FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_algorithm_updated BEFORE UPDATE ON algorithm FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_algorithm_event_updated BEFORE UPDATE ON algorithm_event FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_algorithm_service_updated BEFORE UPDATE ON algorithm_service FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_linkage_rule_updated BEFORE UPDATE ON linkage_rule FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_menu_updated BEFORE UPDATE ON menu FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_resource_updated BEFORE UPDATE ON resource FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_license_updated BEFORE UPDATE ON license FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_firmware_updated BEFORE UPDATE ON firmware FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_system_setting_updated BEFORE UPDATE ON system_setting FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_deployment_updated BEFORE UPDATE ON deployment FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tr_device_platform_updated BEFORE UPDATE ON device_platform FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- SEED DATA: Default Roles
-- ============================================
INSERT INTO role (name, code, description, permissions, status) VALUES
('系统管理员', 'SUPER_ADMIN', '超级管理员，拥有所有权限', '["*"]', 1),
('普通用户', 'USER', '普通用户，基本查看权限', '["user:read", "device:read", "algorithm:read"]', 1),
('运维人员', 'OPERATOR', '运维人员，设备管理权限', '["user:read", "device:*", "algorithm:read"]', 1);

-- ============================================
-- SEED DATA: Default Admin User
-- Password: admin123 (bcrypt hash)
-- ============================================
INSERT INTO users (username, password_hash, phone, email, org_id, role_id, status) VALUES
('admin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '18688888888', 'admin@example.com', 1, 1, 1);

-- ============================================
-- VIEWS: For common queries
-- ============================================

-- Device with organization and region info
-- Note: memory_size and disk_size are stored in bytes (BIGINT).
-- API responses return human-readable strings (e.g., "16G", "256G").
CREATE OR REPLACE VIEW v_device_details AS
SELECT
    d.id,
    d.device_name,
    d.device_sn,
    d.device_ip,
    d.device_port,
    d.device_type,
    dt.name AS device_type_name,
    d.firmware_version,
    d.department,
    d.product_type,
    d.cpu_cores,
    d.cpu_usage,
    d.memory_size,
    d.memory_usage,
    d.disk_size,
    d.disk_usage,
    d.video_source_count,
    d.online_status,
    d.last_heartbeat_at,
    d.auth_status,
    d.auth_expire_time,
    d.region_id,
    r.name AS region_name,
    d.org_id,
    o.name AS org_name,
    d.deleted_at,
    d.created_at,
    d.updated_at,
    CASE
        WHEN d.memory_size >= 1073741824 THEN (d.memory_size / 1073741824.0)::TEXT || 'G'
        WHEN d.memory_size >= 1048576 THEN (d.memory_size / 1048576.0)::TEXT || 'M'
        WHEN d.memory_size >= 1024 THEN (d.memory_size / 1024.0)::TEXT || 'K'
        ELSE d.memory_size::TEXT
    END AS memory_size_fmt,
    CASE
        WHEN d.disk_size >= 1073741824 THEN (d.disk_size / 1073741824.0)::TEXT || 'G'
        WHEN d.disk_size >= 1048576 THEN (d.disk_size / 1048576.0)::TEXT || 'M'
        WHEN d.disk_size >= 1024 THEN (d.disk_size / 1024.0)::TEXT || 'K'
        ELSE d.disk_size::TEXT
    END AS disk_size_fmt
FROM device d
LEFT JOIN dict_device_type dt ON d.device_type = dt.id
LEFT JOIN region r ON d.region_id = r.id
LEFT JOIN org o ON d.org_id = o.id;

-- User with role and org names (excluding password_hash)
CREATE OR REPLACE VIEW v_user_details AS
SELECT
    u.id,
    u.username,
    u.phone,
    u.email,
    u.gender,
    u.avatar,
    u.org_id,
    o.name AS org_name,
    u.role_id,
    r.name AS role_name,
    r.code AS role_code,
    u.status,
    u.last_login,
    u.deleted_at,
    u.created_at,
    u.updated_at
FROM users u
LEFT JOIN role r ON u.role_id = r.id
LEFT JOIN org o ON u.org_id = o.id;

-- ============================================
-- PERMISSIONS (JSONB) Structure Example
-- ============================================
-- Role permissions JSONB format:
-- [
--   "user:read",
--   "user:write",
--   "device:read",
--   "device:write",
--   "device:delete",
--   "algorithm:*",
--   "deployment:read",
--   "deployment:write"
-- ]
-- Or wildcard: ["*"] for superadmin

-- ============================================
-- CONFIG (JSONB) Structure Examples
-- ============================================
-- Data source config:
-- {
--   "url": "rtsp://192.168.1.100:554/stream",
--   "username": "admin",
--   "password": "encrypted_password",
--   "protocol": "rtsp"
-- }

-- Linkage rule conditions:
-- [
--   {"type": "event", "algorithm": "intrusion", "level": "high"},
--   {"type": "time", "start": "08:00", "end": "18:00", "days": [1,2,3,4,5]}
-- ]

-- Linkage rule actions:
-- [
--   {"type": "notify", "channel": "email", "recipients": ["admin@example.com"]},
--   {"type": "record", "duration": 30},
--   {"type": "http", "url": "http://api.example.com/webhook"}
-- ]
